-- 1) Create the database (run from a superuser connection)
-- If your Postgres is v9.4+ you can keep IF NOT EXISTS; otherwise drop it.
CREATE DATABASE employee_directory;

-- 2) Connect to the database (psql meta-command)
\c employee_directory

-- 3) Table definition (Postgres: no backticks, no ENGINE/CHARSET, no AUTO_INCREMENT)
DROP TABLE IF EXISTS employee;

CREATE TABLE employee (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(45),
  last_name  VARCHAR(45),
  email      VARCHAR(255)
);

-- 4) Seed data
INSERT INTO employee (first_name, last_name, email) VALUES
  ('Leslie','Andrews','leslie@luv2code.com'),
  ('Emma','Baumgarten','emma@luv2code.com'),
  ('Avani','Gupta','avani@luv2code.com'),
  ('Yuri','Petrov','yuri@luv2code.com'),
  ('Juan','Vega','juan@luv2code.com');
