-- Drop and recreate the schema
DROP SCHEMA IF EXISTS "hb-01-one-to-one-uni" CASCADE;
CREATE SCHEMA "hb-01-one-to-one-uni";

-- instructor_detail table
CREATE TABLE "hb-01-one-to-one-uni".instructor_detail (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  youtube_channel   VARCHAR(128),
  hobby             VARCHAR(45)
);

-- instructor table
CREATE TABLE "hb-01-one-to-one-uni".instructor (
  id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name             VARCHAR(45),
  last_name              VARCHAR(45),
  email                  VARCHAR(45),
  instructor_detail_id   INTEGER,
  CONSTRAINT fk_detail
    FOREIGN KEY (instructor_detail_id)
    REFERENCES "hb-01-one-to-one-uni".instructor_detail(id)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
);

-- Optional: index to speed up joins on the FK (mirrors MySQL's FK_DETAIL_idx)
CREATE INDEX IF NOT EXISTS idx_instructor_detail_id
  ON "hb-01-one-to-one-uni".instructor (instructor_detail_id);

-- If you want to ENFORCE true 1-to-1 at the DB level, add this UNIQUE constraint:
-- ALTER TABLE "hb-01-one-to-one-uni".instructor
--   ADD CONSTRAINT uq_instructor_detail UNIQUE (instructor_detail_id);
