-- PostgreSQL conversion of your MySQL DDL

-- Drop & recreate the schema
DROP SCHEMA IF EXISTS "hb-05-many-to-many" CASCADE;
CREATE SCHEMA "hb-05-many-to-many";
SET search_path TO "hb-05-many-to-many";

-- instructor_detail
CREATE TABLE instructor_detail (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  youtube_channel VARCHAR(128),
  hobby           VARCHAR(45)
);

-- instructor
CREATE TABLE instructor (
  id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name             VARCHAR(45),
  last_name              VARCHAR(45),
  email                  VARCHAR(45),
  instructor_detail_id   INTEGER,
  CONSTRAINT fk_detail
    FOREIGN KEY (instructor_detail_id)
    REFERENCES instructor_detail (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

-- course
CREATE TABLE course (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title          VARCHAR(128),
  instructor_id  INTEGER,
  CONSTRAINT title_unique UNIQUE (title),
  CONSTRAINT fk_instructor
    FOREIGN KEY (instructor_id)
    REFERENCES instructor (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

-- review
CREATE TABLE review (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  comment    VARCHAR(256),
  course_id  INTEGER,
  CONSTRAINT fk_course
    FOREIGN KEY (course_id)
    REFERENCES course (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

-- student
CREATE TABLE student (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(45),
  last_name  VARCHAR(45),
  email      VARCHAR(45)
);

-- junction table: course_student (many-to-many)
CREATE TABLE course_student (
  course_id  INTEGER NOT NULL,
  student_id INTEGER NOT NULL,
  PRIMARY KEY (course_id, student_id),
  CONSTRAINT fk_course_05
    FOREIGN KEY (course_id)
    REFERENCES course (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_student
    FOREIGN KEY (student_id)
    REFERENCES student (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

-- Helpful indexes (Postgres doesn't auto-create FK indexes)
CREATE INDEX idx_instructor_detail_id ON instructor (instructor_detail_id);
CREATE INDEX idx_course_instructor_id  ON course (instructor_id);
CREATE INDEX idx_review_course_id      ON review (course_id);
-- Composite PK already covers course_id lookups; add one for student_id-only lookups:
CREATE INDEX idx_course_student_student_id ON course_student (student_id);
