-- PostgreSQL conversion of your MySQL DDL

-- Drop & recreate the schema (drops all contained objects)
DROP SCHEMA IF EXISTS "hb-04-one-to-many-uni" CASCADE;
CREATE SCHEMA "hb-04-one-to-many-uni";
SET search_path TO "hb-04-one-to-many-uni";

-- instructor_detail
CREATE TABLE instructor_detail (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  youtube_channel VARCHAR(128),
  hobby           VARCHAR(45)
);

-- instructor
CREATE TABLE instructor (
  id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name             VARCHAR(45),
  last_name              VARCHAR(45),
  email                  VARCHAR(45),
  instructor_detail_id   INTEGER,
  CONSTRAINT fk_detail
    FOREIGN KEY (instructor_detail_id)
    REFERENCES instructor_detail (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

-- course
CREATE TABLE course (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title          VARCHAR(128),
  instructor_id  INTEGER,
  CONSTRAINT title_unique UNIQUE (title),
  CONSTRAINT fk_instructor
    FOREIGN KEY (instructor_id)
    REFERENCES instructor (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

-- review
CREATE TABLE review (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  comment    VARCHAR(256),
  course_id  INTEGER,
  CONSTRAINT fk_course
    FOREIGN KEY (course_id)
    REFERENCES course (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

-- Helpful indexes for FK columns (Postgres doesn't auto-create these)
CREATE INDEX idx_instructor_detail_id ON instructor (instructor_detail_id);
CREATE INDEX idx_course_instructor_id  ON course (instructor_id);
CREATE INDEX idx_review_course_id      ON review (course_id);
