spring.application.name=advanced-mappings
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=hb-01-one-to-one-uni
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.root=warn

logging.level.org.hibernate.SQL=trace